### ISSUE TITLE
线条显示异常

### ISSUE THREAD

**Issue by Yuuko755** [zhouzhuo810/ZzWeatherView#3]
WeatherView的onDraw一直在循环，设置默认显示7条，但是滑动的时候后面未显示出来的两条曲线会默认链接到最顶端，手动滑动一遍后就正常显示了，这是什么原因？

**Comment by zhouzhuo810** [comment]
你放在哪里显示的

**Comment by Yuuko755** [comment]
已经解决了，把硬件加速开启后就显示正常了，谢谢回复

**Comment by zhouzhuo810** [comment]
好的
